defmodule LoggerDashboardWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :logger_dashboard

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  #
  # `max_age` is stated rather than inherited: a session carries a digest of the token
  # that established it, so it cannot outlive a rotation, and eight hours is simply how
  # long one is good for. It has to be a decision somebody made, not a library default
  # nobody looked at.
  @session_max_age 8 * 60 * 60

  @session_options [
    store: :cookie,
    key: "_logger_dashboard_key",
    signing_salt: "AgFsn3Bi",
    same_site: "Lax",
    max_age: @session_max_age
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :logger_dashboard,
    gzip: not code_reloading?,
    only: LoggerDashboardWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug LoggerDashboardWeb.Router
end
